language: php

php:
  - 5.3
  - 5.4

env:
  - MONGO_VERSION=1.2.12
  - MONGO_VERSION=1.3.4

services: mongodb

before_script:
  - curl --silent http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script: phpunit --coverage-text

notifications:
  email:
    - tim+dough@nagel.com.au
